Login page 1.1
viaMover/web-app pull request #107
Opened 2021-09-20 14:23 UTC by trukach000

Login page 1.1
web3modal (vue edition) + QR code lib for WC

2021-09-20 15:33 UTC, Sinu5oid requested changes
Also the whole `@/settings/persist/last-provider` module seems to be unused. Please perform a cleanup

2021-09-20 15:33 UTC, Sinu5oid commented on src/views/connect-wallet.vue
> +      console.log(provider);
Remove console.log

2021-09-20 15:33 UTC, Sinu5oid commented on src/views/connect-wallet.vue
> +    qrModal.open = async (uri: string) => {
I don't really see any reason to defer object composition is such way. Why not composing in-place?

```typescript
const qrModal = {
    open: async (uri: string) => {
        const qrCodeUri = await QRCode.toDataURL(uri);
        this.wcCode = qrCodeUri;
    },
    close: () => {
        console.info('Modal closed');
    }
}
```

Also the `close` hook is never used (or should be unused anyway)

2021-09-20 15:33 UTC, Sinu5oid commented on src/views/connect-wallet.vue
> +      console.log(provider);
Same here

2021-09-20 15:33 UTC, Sinu5oid commented on src/router/wallet-auth-guard.ts
> +    walletReady = await store.dispatch('account/waitWallet');
`walletReady` should be declared here

2021-09-20 15:33 UTC, Sinu5oid commented on src/router/wallet-auth-guard.ts
> +    walletReady = await store.dispatch('account/waitWallet');
Also `isWalletReady` would be more descriptive

2021-09-20 15:33 UTC, Sinu5oid commented on src/store/modules/account/actions/wallet.ts
> -      setLastProviderToPersist(payload.providerName);
Since you removed this line, you should also delete unused import `setLastProviderToPersist`

2021-09-20 15:33 UTC, Sinu5oid commented on src/store/modules/account/actions/wallet.ts
> -    clearLastProviderPersist();
Same here (`clearLastProviderPersist`)

2021-09-20 17:18 UTC, bog5651 commented on src/app.vue
> +import { InitWalletPayload } from './store/modules/account/actions/wallet';
Sort import plz

2021-09-20 17:18 UTC, bog5651 commented on src/styles/_general.less
> +  font-family: 'Bold';
missing `, sans serif` and `font-weight: XXX;`

At all styles

2021-09-20 17:18 UTC, bog5651 commented on src/styles/_general.less
> +  color: rgba(60,60,67,0.6);
I am not shure, but I think, there is missing spaces. Check linter plz

2021-09-20 17:18 UTC, bog5651 commented on src/styles/_general.less
> +}
and there is missing empty line

2021-09-20 17:18 UTC, bog5651 commented on src/views/connect-wallet.vue
> +          Mover is a non-custodial service. It means that you need to connect
Put text in I18n, plz

2021-09-20 17:18 UTC, bog5651 commented on src/views/connect-wallet.vue
> +          <img alt="" :src="wcCode" />
Can we use our tag for picture/image here?

And missing Alt

2021-09-20 17:37 UTC, Sinu5oid commented on src/views/connect-wallet.vue
> +          <img alt="" :src="wcCode" />
I think this is the case when `<custom-picture>` will not be useful as there are no alternative sources, PNG only

Also the component should be updated to take optional PNG sources as well as WEBP one

2021-09-22 10:37 UTC, Sinu5oid requested changes

2021-09-22 10:37 UTC, Sinu5oid commented on src/views/connect-wallet.vue
> +        </p>
This could (and should) be done with `<i18n>` functional component
Check the [docs](https://kazupon.github.io/vue-i18n/guide/interpolation.html#basic-usage) and [example](https://github.com/kazupon/vue-i18n/blob/dev/examples/interpolation/places/index.html) as well as how it was [already done ](https://github.com/viaMover/web-app/blob/640075c3a7998c27f6b3ff201e04feceeb5c3fe2/src/views/nft/nft-view-vaults.vue#L6-L14)in the project

2021-09-22 10:37 UTC, Sinu5oid commented on src/views/connect-wallet.vue
> +    };
Remove unused

2021-09-22 10:37 UTC, Sinu5oid commented on src/i18n/messages/en.ts
> +    chooseProvider: 'Choose from Metamask and other popular wallets'
We almost always use prefixes/suffixes like `lbl`, `txt`, `btn`, etc for non-group keys (e.g. `menu` is a translation group as well as `savings` or `treasury`, when `lblSwapToken` is not)

2021-09-22 10:37 UTC, Sinu5oid commented on src/styles/_general.less
> +  font-family: 'Medium';
```suggestion
  font-family: 'Medium', sans-serif;
  font-weight: 500;
```

2021-09-22 10:37 UTC, Sinu5oid commented on src/styles/_general.less
> +  font-family: 'Regular';
```suggestion
  font-family: 'Regular', sans-serif;
  font-weight: 400;
```

2021-09-22 10:37 UTC, Sinu5oid commented on src/styles/_general.less
> +  font-family: 'Regular';
```suggestion
  font-family: 'Regular', sans-serif;
  font-weight: 400;
```

2021-09-22 13:47 UTC, Sinu5oid approved these changes
LGTM :rocket:

2021-09-22 14:48 UTC, merged