Feature/savings
viaMover/web-app pull request #112
Opened 2021-09-24 13:30 UTC by bog5651

2021-10-01 14:58 UTC, bog5651 commented on src/components/modals/search-modal/search-modal.vue
> +      console.log('PAYLOAD:', newVal);
remove console.log

2021-10-01 14:58 UTC, bog5651 commented on src/components/savings/savings-deposit-review.vue
> +import { sameAddress } from '@/utils/address';
sort imports

2021-10-01 14:58 UTC, bog5651 commented on src/components/savings/savings-empty.vue
> +import { formatPercents } from '@/utils/format';
sort imports

2021-10-01 14:58 UTC, bog5651 commented on src/components/savings/savings-empty.vue
> +      return '~ $984.17';
looks like stub. Plz add real value

2021-10-01 14:58 UTC, bog5651 commented on src/components/savings/savings-left-rail.vue
> +import { formatToNative } from '@/utils/format';
sort imports

2021-10-01 14:58 UTC, bog5651 commented on src/components/savings/savings-withdraw-form.vue
> +        ></dynamic-input>
` ></dynamic-input>` ->  `/>`

2021-10-01 14:58 UTC, bog5651 commented on src/components/savings/savings-withdraw-form.vue
> +        console.info('Savings withdraw action gaslimit:', actionGasLimit);
may be remove this logs? Target users whatever does not see this logs (like the ones above)

2021-10-01 14:58 UTC, bog5651 commented on src/settings/globals.ts
> +  isGovernanceEnabled: true,
false

2021-10-01 14:58 UTC, bog5651 commented on src/views/savings/savings-deposit-wrapper.vue
> +import { sameAddress } from '@/utils/address';
sort imports

2021-10-01 14:58 UTC, bog5651 commented on src/views/savings/savings-deposit-wrapper.vue
> +          async () => {
```
 async (step: string) => {
            this.txStep = step;
          },
```

2021-10-01 14:58 UTC, bog5651 commented on src/views/savings/savings-withdraw-wrapper.vue
> +          async () => {
```
async (step: string) => {
            this.txStep = step;
          }
```

2021-10-02 15:26 UTC, Sinu5oid requested changes

2021-10-02 15:26 UTC, Sinu5oid commented on src/components/savings/savings-deposit-review.vue
> +        return 'No data';
Move to the i18n

2021-10-02 15:26 UTC, Sinu5oid commented on src/components/savings/savings-empty.vue
> +      return '~ $984.17';
Yup, it's definitely a stub

2021-10-02 15:26 UTC, Sinu5oid commented on src/components/savings/savings-form-loader.vue
> +        }
Localize this

2021-10-02 15:26 UTC, Sinu5oid commented on src/components/savings/savings-manage.vue
> +      popoverParentId: 'savings-manage-action-buttons'
Is this needed? There was a popover, now I don't see any

2021-10-02 15:26 UTC, Sinu5oid commented on src/components/savings/savings-withdraw-form.vue
> +} from '@/wallet/actions/subsidized';
Imports aren't sorted

2021-10-02 15:26 UTC, Sinu5oid commented on src/components/savings/savings-withdraw-form.vue
> +      process: false
`process` what? TO process something (as a callback?) or A/THE process (an action in time?)
`isProcessing`, `isLoading`, `isBusy`, `isEstimating` -- anything would be better

2021-10-02 15:26 UTC, Sinu5oid commented on src/components/savings/savings-withdraw-form.vue
> +    ]),
The same object-like pattern

Duplicated `...mapGetters('account, [...]),` needs to be merged

2021-10-02 15:26 UTC, Sinu5oid commented on src/components/savings/savings-withdraw-review.vue
> +    formatEstimatedGasCost(): string {
same here

2021-10-02 15:26 UTC, Sinu5oid commented on src/components/savings/savings-withdraw-review.vue
> +          class="shadow"
Do we have such class?

2021-10-02 15:26 UTC, Sinu5oid commented on src/components/savings/savings-withdraw-review.vue
> +          <span />
Why?

2021-10-02 15:26 UTC, Sinu5oid commented on src/components/savings/savings-withdraw-review.vue
> +      isSmartTreasury: true as boolean,
`as boolean` adds unnecessary verbosity

2021-10-02 15:26 UTC, Sinu5oid commented on src/components/statements/statement-list/statement-list.vue
> +    <h1 v-if="title !== ''" class="list-title">
In this configuration the `<slot>` is useless

2021-10-02 15:26 UTC, Sinu5oid commented on src/components/statements/statement-list/statement-list.vue
> +    <p v-if="description !== ''" class="list-description">
Same here

2021-10-02 15:26 UTC, Sinu5oid commented on src/i18n/messages/en.ts
> +      lblWhatDoWeDeposit: 'What we do deposit',
What do we deposit

2021-10-02 15:26 UTC, Sinu5oid commented on src/i18n/messages/en.ts
> +      txtDepositShortDescription: 'Get 8.3% APY on simple savings in USDC',
`8.3%` is a dynamic value, should be computed elsewhere

2021-10-02 15:26 UTC, Sinu5oid commented on src/router/index.ts
> +    name: 'savings-root',
Root component with `children` should not have a name (as the Vue Router doc states; also it produces runtime warnings)

2021-10-02 15:26 UTC, Sinu5oid commented on src/router/index.ts
> +    name: 'savings-root',
default component with `path: ''` should be used instead

2021-10-02 15:26 UTC, Sinu5oid commented on src/views/savings/savings-deposit-wrapper.vue
> +          async () => {
Not really sure, seems like valid callback if the `depositCompound()` needs to change the step to the predefined one

2021-10-02 15:26 UTC, Sinu5oid commented on src/views/savings/savings-deposit-wrapper.vue
> +        console.error('action gas limit is empty during `handleTxStart`');
Everything is the same -- here and there

2021-10-02 15:26 UTC, Sinu5oid commented on src/views/savings/savings-manage-wrapper.vue
> +  </div>
`<div>` is unnecessary here as long as `v-if` is complete (produces one and only one output)

2021-10-02 15:26 UTC, Sinu5oid commented on src/views/savings/savings-root.vue
> +        <component :is="'savings-left-rail'" />
I don't see how this is changed from somewhere
If it's not -- leave it as `<savings-left-rail>`

2021-10-02 15:26 UTC, Sinu5oid commented on src/views/savings/savings-withdraw-wrapper.vue
> +    ...mapState('account', ['networkInfo', 'currentAddress', 'provider']),
Same here, the same comments as before

2021-10-02 15:26 UTC, Sinu5oid commented on src/wallet/actions/subsidized.ts
>    console.log('fastGasPriceGWEI;', fastGasPriceGWEI);
Here they are

2021-10-02 15:26 UTC, Sinu5oid commented on src/wallet/actions/subsidized.ts
>    console.log('treasuryBonus (native):', treasuryBonus);
And you as well

2021-10-02 15:26 UTC, Sinu5oid commented on src/wallet/actions/subsidized.ts
> +  console.log('fastTransactionPriceNative:', fastTransactionPriceNative);
More `console.log()`s

2021-10-02 15:38 UTC, trukach000 commented on src/components/controls/dynamic-input.vue
> +    }
It's just a method to pass all listeners from the root component to the nested one with a little modification.
I used 'unknown' type just for speed , if u know the right type feel free to suggest )

2021-10-02 15:43 UTC, trukach000 commented on src/components/savings/savings-deposit-form.vue
> +        console.error(`transfer error: ${err}`);
I guess for some errors like this it's better to exist to understand the way of error rising coz sentry saves then into the context

2021-10-04 13:53 UTC, trukach000 commented on src/components/savings/savings-withdraw-review.vue
> +          class="shadow"
.shadow {
        filter: drop-shadow(0 4px 16px #ccc);
      }

2021-10-04 13:55 UTC, trukach000 commented on src/components/savings/savings-withdraw-review.vue
> +          <span />
![image](https://user-images.githubusercontent.com/2332431/135864040-d93d844d-1203-44c4-9651-03d4be287330.png)
each span for each arrow

2021-10-04 13:59 UTC, trukach000 commented on src/components/statements/statement-list/statement-list.vue
> +    <h1 v-if="title !== ''" class="list-title">
Why?

2021-10-04 14:24 UTC, Sinu5oid requested changes

2021-10-04 14:24 UTC, Sinu5oid commented on src/components/savings/savings-left-rail.vue
> +        alt: '',
missing alt

2021-10-04 14:24 UTC, Sinu5oid commented on src/components/savings/savings-left-rail.vue
> +        //TODO insert new image
same here

2021-10-04 14:24 UTC, Sinu5oid commented on src/components/savings/savings-left-rail.vue
> +        //TODO insert new image
There should be a new image, I believe

2021-10-04 14:24 UTC, Sinu5oid commented on src/components/sections/menu-section.vue
> +    }
I am not quite following the idea behind async/await call of `this.$router.push`
Synchronous one would be as effective as asynchronous

2021-10-04 14:24 UTC, Sinu5oid commented on src/store/modules/account/mutations/transactions.ts
> +import { Transaction } from './../../../../wallet/types';
replace with `@/wallet/types`

2021-10-04 14:24 UTC, Sinu5oid commented on src/store/modules/nft/mutations.ts
> +import { DiceData } from './../../../services/chain/nft/dice/types';
`@/services/chain/nft/dice/types`

But ideally it should be imported as `@/services` or `@/services/chain` or `@/services/chain/nft/dice`

Same goes for Vaults

2021-10-04 14:24 UTC, Sinu5oid commented on src/views/nft/nft-view-dice.vue
>  import { DicePayload } from '@/store/modules/nft/actions/claim';
Same here
Kinda optional but nonetheless

2021-10-04 14:24 UTC, Sinu5oid commented on src/views/nft/nft-view-dice.vue
> +import EmojiTextButton from '@/components/buttons/emoji-text-button.vue';
I believe they are exported as `@/components/buttons`

2021-10-04 14:24 UTC, Sinu5oid commented on src/views/nft/nft-view-sweet-and-sour.vue
> +import ActionButton from '@/components/buttons/action-button.vue';
Same here

2021-10-04 14:24 UTC, Sinu5oid commented on src/views/nft/nft-view-unexpected-move.vue
> +import EmojiTextButton from '@/components/buttons/emoji-text-button.vue';
Same here

2021-10-04 14:24 UTC, Sinu5oid commented on src/wallet/actions/approve/needApprove.ts
> +import { fromWei, greaterThan } from './../../../utils/bigmath';
Imports can be shortened

2021-10-04 14:24 UTC, Sinu5oid commented on src/wallet/actions/savings/deposit/depositSubsidized.ts
> +import { Transaction } from './../../../types';
Same here

2021-10-04 14:24 UTC, Sinu5oid commented on src/wallet/actions/savings/withdraw/withdrawSubsidized.ts
> +import { createSavingsWithdrawActionString } from './../../subsidized';
Same here

2021-10-04 14:24 UTC, Sinu5oid commented on src/wallet/actions/swap/swap.ts
> +import { executeTransactionWithApprove } from './../actionWithApprove';
Same here

2021-10-04 14:24 UTC, Sinu5oid commented on src/wallet/actions/swap/swapSubsidized.ts
> +import { Transaction } from './../../types';
And here

2021-10-04 14:24 UTC, Sinu5oid commented on src/wallet/ethPrice.ts
> +import { currentTimestamp } from './../utils/time';
And here

2021-10-04 14:24 UTC, Sinu5oid commented on src/wallet/gas.ts
> +import { isError, isSuccess } from './../services/responses';
And here

2021-10-04 14:24 UTC, Sinu5oid commented on src/wallet/offchainExplorer.ts
> +import { getTransactionReceiptMined } from './../web3/transaction';
And here

2021-10-04 14:24 UTC, Sinu5oid commented on src/wallet/references/data.ts
> +import { SmallTokenInfoWithIcon, Token } from './../types';
And here

2021-10-04 14:29 UTC, Sinu5oid commented on src/components/statements/statement-list/statement-list.vue
> +    <h1 v-if="title !== ''" class="list-title">
Just because <slot> is scoped with conditionally rendered title
Case 1 (has `:title` prop):
```vue
<component :title />
```

Case 2 (has no `:title` prop, `<template v-slot:title>` used instead):
```vue
<component>
  <template v-slot:title>
    <h1 class="list-title custom-title">{{ myCustomText }}</h1>
  </template>
</component>
```

But in your case the absence of `:title` prop makes slot inaccessible

2021-10-05 14:07 UTC, trukach000 commented on src/components/sections/menu-section.vue
> +    }
![image](https://user-images.githubusercontent.com/2332431/136039495-260a7c9a-4570-4a3e-8874-c4979416b08a.png)

2021-10-05 16:07 UTC, Sinu5oid approved these changes
LGTM :rocket:
It's time to test in on staging

2021-10-06 16:21 UTC, merged