[Feature] Unify Components
viaMover/web-app pull request #159
Opened 2021-11-05 05:59 UTC by bog5651

Recently, a massive repetition of the same code has begun. To fix this situation, the following was done:

- add prepare-from for remove same components (like treasury-increase-form.vue, savings-deposit-form.vue etc.)
- add review-form for the same purpose
- remove legacy components
- move 'full-page-loader' to forms directory and rename to 'loader-form'
- add index.ts files for form directory
- remove index.ts from loader-form directory (unusable)
- update import lines
- rename some types
- fix description for decrease from (later use text from increase)

(important) That first iteration for remove same components

2021-11-05 09:44 UTC, Sinu5oid requested changes
Besides already mentioned changes, I would like to also have savings using unified forms
(Even not mentioning that after localization changes, the savings module uses fallback strings instead of actual ones)

2021-11-05 09:44 UTC, Sinu5oid commented on src/components/forms/prepare-form/prepare-form.vue
> +      return !sameAddress(this.asset.address, this.outputUSDCAsset.address);
In case of ETH as a base asset, there would be another condition to evaluate (`isEth(address)`, if I remember it correctly)

So everything described above leads us to the need of introducing base currency as a prop asset or dedicating this whole logic to the outer wrapper component. I would probably stick to the second (as there are cases with two base assets -- USDC and (W)ETH)

2021-11-05 09:44 UTC, Sinu5oid commented on src/components/forms/prepare-form/prepare-form.vue
> +        <action-button
For action buttons I would personally rather use form-originated event (both `Enter` and button click (in any scenario) would work). You can find an example in `feature/earnings` -- there were `type` and `propagate-original-event` props available to the components using `<action-button>`

2021-11-05 09:44 UTC, Sinu5oid commented on src/components/forms/prepare-form/prepare-form.vue
> +        <action-button
To do so, there should be a `<form>` html tag with `@submit.prevent="handleSubmit"` event listener. I didn't find a `<form>` in the `<prepare-form>` btw :D

2021-11-05 09:44 UTC, Sinu5oid commented on src/components/forms/review-form.vue
> +        <h2>{{ `${inputAmountTitle} ${token.symbol}` }}</h2>
This is bad for performance, it's better to use separate brackets instead
```suggestion
        <h2>{{ inputAmountTitle }} {{ token.symbol }}</h2>
```
Or if the text appears joined with `''` and it shouldn't do so, use `&nbsp;` symbol (non-breaking space)

2021-11-05 09:44 UTC, Sinu5oid commented on src/components/forms/review-form.vue
> +    formatToNative,
As they are not used in the template, there's no need to include them as vm.`methods`

2021-11-05 09:44 UTC, Sinu5oid commented on src/views/treasury/treasury-claim-and-burn-wrapper.vue
> +            this.transferError = this.$t('treasury.claimAndBurn.lblBurnError');
as string?

2021-11-05 09:44 UTC, Sinu5oid commented on src/views/treasury/treasury-claim-and-burn-wrapper.vue
> +            this.transferError = this.$t('treasury.claimAndBurn.lblBurnError');
Here and below

2021-11-05 11:43 UTC, Sinu5oid commented on src/components/forms/prepare-form/prepare-form.vue
> +    handleOpenSelectModal() {
```suggestion
    handleOpenSelectModal(): void {
```

2021-11-05 11:43 UTC, Sinu5oid commented on src/components/forms/prepare-form/prepare-form.vue
> +    handleSelectMaxAmount() {
```suggestion
    handleSelectMaxAmount(): void {
```

2021-11-06 07:52 UTC, Sinu5oid requested changes

2021-11-08 05:44 UTC, bog5651 commented on src/styles/_common.less
> + linear-gradient(-135deg, transparent 50%, var(--bgColor) 0) no-repeat 100% ~'0 / 12px 12px',
That var use in `EmojiCard`

2021-11-08 09:08 UTC, Sinu5oid commented on src/styles/_common.less
> + linear-gradient(-135deg, transparent 50%, var(--bgColor) 0) no-repeat 100% ~'0 / 12px 12px',
Fair enough. If this is really used then let's keep it. In any case the whole css bundle will be replaced eventually

2021-11-08 12:32 UTC, trukach000 approved these changes

2021-11-09 08:13 UTC, Sinu5oid approved these changes

2021-11-09 08:15 UTC, merged