[Feature] Nibble shop, Redeem page
viaMover/web-app pull request #193
Opened 2021-12-17 13:31 UTC by trukach000

Added Nibble Shop.

Added claim and redeem functionality.

2021-12-17 15:34 UTC, bog5651 requested changes

2021-12-17 15:34 UTC, bog5651 commented on src/components/debit-card/manage/debit-card-manage-order-card.vue
> +          @submit.prevent="handleRedeem"
Missing handleRedeem in methods

2021-12-17 15:34 UTC, bog5651 commented on src/services/chain/shop/token.ts
> +        changeStep('Process');
Can rename to `changeStepToProcess` and remove arg

2021-12-17 15:34 UTC, bog5651 commented on src/services/chain/shop/token.ts
> +        changeStep('Process');
same here

2021-12-17 15:34 UTC, bog5651 commented on src/settings/globals.ts
> +  isVaultsRaceEnabled: true
false

2021-12-17 15:34 UTC, bog5651 commented on src/store/modules/shop/actions/claim.ts
> +  changeStep: (step: Step) => void;
and Here

2021-12-17 15:34 UTC, bog5651 commented on src/store/modules/shop/mutations.ts
> +        ...(data.asset.initialQuantity !== undefined && {
```suggestion
        ...(data.asset.initialQuantity && {
```

2021-12-17 15:34 UTC, bog5651 commented on src/store/modules/shop/mutations.ts
> +        ...(data.asset.initialQuantity !== undefined && {
```suggestion
        ...(data.asset.initialQuantity && {
```

2021-12-17 15:34 UTC, bog5651 commented on src/views/vaults-race/vaults-race-root.vue
> +        <component :is="'vaults-race-left-rail'" />
use real component

2021-12-17 15:39 UTC, trukach000 commented on src/components/debit-card/manage/debit-card-manage-order-card.vue
> +          @submit.prevent="handleRedeem"
Typo, will fix

2021-12-17 15:39 UTC, trukach000 commented on src/settings/globals.ts
> +  isVaultsRaceEnabled: true
Right

2021-12-17 15:42 UTC, trukach000 commented on src/store/modules/shop/mutations.ts
> +        ...(data.asset.initialQuantity !== undefined && {
The idea is - overwrite the hard coded value in case of defined value here. 0 is meaningful value but it won't override in your proposal.

2021-12-17 15:43 UTC, trukach000 commented on src/views/vaults-race/vaults-race-root.vue
> +        <component :is="'vaults-race-left-rail'" />
Vault is out of scope right now, I will fix it late

2021-12-17 20:41 UTC, Sinu5oid requested changes
Also I am not a big fan of logging errors near the callee
Move `Sentry.captureException(error)` as close to the potential failure points as possible, the View layer should not be responsible for that

2021-12-17 20:41 UTC, Sinu5oid commented on src/store/modules/shop/actions/redeem.ts
> +import { ShopStoreState } from './../types';
```suggestion
import { ShopStoreState } from '../types';
```

2021-12-17 20:41 UTC, Sinu5oid commented on src/store/modules/shop/actions/redeem.ts
> +import { checkAccountStateIsReady } from './../../account/utils/state';
```suggestion
import { checkAccountStateIsReady } from '../../account/utils/state';
```

2021-12-17 20:41 UTC, Sinu5oid commented on src/views/nibble-shop/nibble-shop-redeem.vue
> +      this.$router.push({ name: 'not-found-route' });
`return` will be useful here to avoid operations on unmounted components while navigating

2021-12-17 20:41 UTC, Sinu5oid commented on src/views/nibble-shop/nibble-shop-redeem.vue
> +      redeemNibbleNFTChain: 'redeemNibbleNFTChain'
Not sure I am following the naming here
If a function is an action then it should be represented as a verb (?) and have a `to <action>` semantic
e.g. `refreshAssetsInfoList` = ✅ and `nibbleShopRedeemServerRequest` = ❌

2021-12-17 20:41 UTC, Sinu5oid commented on src/views/nibble-shop/nibble-shop-redeem.vue
> +    status(validation: Validation) {
Missing function return type

2021-12-17 20:41 UTC, Sinu5oid commented on src/views/nibble-shop/nibble-shop-view.vue
> +import { SimpleLoaderModal } from '@/components/modals';
Empty line between imports and SFC is mandatory

2021-12-17 20:41 UTC, Sinu5oid commented on src/views/nibble-shop/nibble-shop-view.vue
> +      this.$router.push({ name: 'not-found-route' });
return

2021-12-17 20:41 UTC, Sinu5oid commented on src/wallet/references/abi/nft-nibble-shop.json
> +{}
ABI contains an array on top level, not an object
(no need to fix as new smart contract will be deployed and we'll get the ABI anyway)

2021-12-17 20:41 UTC, Sinu5oid commented on src/wallet/references/data.ts
> +    NFT_CEO_OF_MONEY: '0x1',
Unused (yet?)

2021-12-17 20:44 UTC, Sinu5oid commented
Please also fix this router issue
```
[vue-router] Named Route 'vaults-race' has a default child route. When navigating to this named route (:to="{name: 'vaults-race'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead.
```

2021-12-17 21:16 UTC, Sinu5oid requested changes

2021-12-17 21:16 UTC, Sinu5oid commented on src/views/nibble-shop/nibble-shop-redeem.vue
> +      valid: vStringNum,
Address should not be validated like this
Considered that streets in France could (potentially, not sure) have an apostrophe, Japanese symbols are not included in regex, there is a Mamina-Sibiryaka street in Russian Federation (as an example of hyphenated names), an address consists of several comma-divided parts (as an example of complex address), we should just pass the address to the API and let it deal with it

2021-12-17 21:16 UTC, Sinu5oid commented on src/views/nibble-shop/nibble-shop-redeem.vue
> +      valid: vStringNum,
Postal code is also poorly validated

2021-12-17 21:16 UTC, Sinu5oid commented on src/views/nibble-shop/nibble-shop-redeem.vue
> +      email: '',
You could try to use saved in card store email (if available during the very same session). Just a small convenient thing to make
(no need to implement)

2021-12-17 21:18 UTC, Sinu5oid commented
Also found:
![image](https://user-images.githubusercontent.com/13100095/146608968-3be9ebb1-563f-4c4e-a6ae-7cddd37af23a.png)
Not sure if the modal should have paddings but else it appears broken

I would also reconsider using regular/medium small-size fonts on this form (as we try to keep UI consistent)
If we agree that this form stays the same then error message top padding should also be tweaked according to its closest `<input>` node

2021-12-18 11:00 UTC, Sinu5oid commented on src/services/chain/shop/token.ts
> +        changeStep('Process');
TBD: Use `changeStep(step: FormStep)` closure

2021-12-18 11:12 UTC, Sinu5oid requested changes

2021-12-18 11:12 UTC, Sinu5oid commented on src/services/mover/nibble-shop/types.ts
> +import { MoverResponse } from './../responses';
```suggestion
import { MoverResponse } from '../responses';
```

2021-12-18 11:12 UTC, Sinu5oid commented on src/store/modules/shop/actions/init.ts
> +import { checkAccountStateIsReady } from './../../account/utils/state';
```suggestion
import { checkAccountStateIsReady } from '../../account/utils/state';
```

2021-12-18 11:12 UTC, Sinu5oid commented on src/views/nibble-shop/nibble-shop-redeem.vue
> +const vStringNum = helpers.regex('vStringNum', /^[a-zA-Z0-9_ ]*$/i);
Remove this

2021-12-18 17:08 UTC, Sinu5oid commented on src/views/nibble-shop/nibble-shop-redeem.vue
> +            <span v-if="!$v.email.required" class="error-message small-font">
missing invalid email validation message

2021-12-18 17:10 UTC, Sinu5oid approved these changes
Let's fix last issues then merge it
It's time to test on staging

2021-12-19 08:38 UTC, merged