[FEATURE][Claim&Burn MOBO]: design and mock net func
viaMover/web-app pull request #202
Opened 2021-12-21 10:37 UTC by bog5651

add new section "claim & burn" with MOBO
add mock contract api function
add i18n texts for new section
fix claim & burn MOVE review page's texts

2021-12-24 12:21 UTC, Sinu5oid requested changes

2021-12-24 12:21 UTC, Sinu5oid commented on src/views/treasury/treasury-claim-and-burn-mobo-wrapper.vue
> +      this.transferError = 'TODO error';
Resolve TODO

2021-12-24 12:21 UTC, Sinu5oid commented on src/components/forms/prepare-form/prepare-form.vue
> +      if (this.transferError !== undefined) {
Any transfer error has the lowest priority over local component conditions that are caused by user action. Not sure why you moved this block
Can you please explain that?

2021-12-24 12:21 UTC, Sinu5oid commented on src/views/treasury/treasury-claim-and-burn-mobo-wrapper.vue
> +        <span class="input-span">{{ value }}</span>
I think it's better to use the same input but with the `disabled` attribute set to make it read-only (similar to the first field of redeeming form). It will keep the structure of components the same but at the same time will do what's needed

2021-12-28 09:06 UTC, trukach000 commented on src/i18n/messages/en.ts
> +      lblDontHaveMOBO: `You don't have any MOBO to convert to UDSC`
typo - `UDSC`->`USDC`

2021-12-28 09:14 UTC, trukach000 commented on src/views/treasury/treasury-claim-and-burn-mobo-wrapper.vue
> +      isSubsidizedEnabled: false,
you can remove this

2021-12-28 09:26 UTC, trukach000 commented on src/wallet/actions/treasury/claimAndBurnMobo/claimAndBurnMoboEstimate.ts
> +    isApproveNeeded = await needApprove(
remove approve logic from here

2021-12-28 10:56 UTC, Sinu5oid requested changes

2021-12-28 10:56 UTC, Sinu5oid commented on src/views/treasury/treasury-claim-and-burn-mobo-wrapper.vue
> +  name: 'TreasuryClaimAndBurnMOBOWrapper',
The canonical name would be `TreasuryClaimAndBurnMoboWrapper` due to snake case translation
Your variant would be translated as `<treasury-claim-and-burn-m-o-b-o-wrapper ...>` if used inside the template whereas the canonical name would be `<treasury-claim-and-burn-mobo-wrapper ...>`

2021-12-28 10:56 UTC, Sinu5oid commented on src/views/treasury/treasury-claim-and-burn-mobo-wrapper.vue
> +        console.error(err);
The error needs a descriptive prefix message like `console.error('failed to handle transaction review', err);`

2021-12-28 10:56 UTC, Sinu5oid commented on src/views/treasury/treasury-claim-and-burn-mobo-wrapper.vue
> +        console.log('Treasury claim and burn MOBO txn reverted');
Since we already display this message, it is worth mentioning the error itself
e.g. `console.log('Treasury claim and burn MOBO txn reverted', err);`

2021-12-28 10:56 UTC, Sinu5oid commented on src/wallet/actions/treasury/claimAndBurnMobo/claimAndBurnMobo.ts
> +  console.log('Executing treasury claim and burn MOBO...');
Isn't needed here

2021-12-28 10:56 UTC, Sinu5oid commented on src/wallet/actions/treasury/claimAndBurnMobo/claimAndBurnMobo.ts
> +    console.error(
Avoid string interpolation whenever it's possible
`console.error` has a convenient API that allows errors to be passed alongside the message: https://developer.mozilla.org/en-US/docs/Web/API/Console/error

The same goes for the lines above with receipt, hash (hash is valid strinterp item, no need to fix), error inside of `console.log`s

2021-12-28 10:56 UTC, Sinu5oid commented on src/wallet/actions/treasury/claimAndBurnMobo/claimAndBurnMoboEstimate.ts
> +  console.log('Estimating treasury claim and burn MOBO...');
Also not needed

2021-12-28 10:56 UTC, Sinu5oid commented on src/wallet/actions/treasury/claimAndBurnMobo/claimAndBurnMoboEstimate.ts
> +    console.error(
Same here

2021-12-29 11:19 UTC, Sinu5oid approved these changes

2021-12-30 09:51 UTC, trukach000 approved these changes

2021-12-30 09:51 UTC, merged