Home page
viaMover/web-app pull request #21
Opened 2021-08-05 11:34 UTC by bog5651

- add visibility flag for deposit card in store
- add menu section
- add link to menu section
- add modals to home-page
- add emoji-card component
- add card component
- add nav bar
- add search form in transaction list
- styling 404 page
- some style-fix
- remove legacy component

2021-08-06 07:48 UTC, Sinu5oid requested changes

2021-08-06 07:48 UTC, Sinu5oid commented on src/components/home/menu-list/menu-list-emoji-card-item.vue
> +    navigateTo(): Record<string, string> {
There is a `Route` type from vue-router. You should use it

2021-08-06 07:48 UTC, Sinu5oid commented on src/components/home/menu-list/menu-list-emoji-card-item.vue
> +        name: this.navigateToName
This will produce runtime errors. You should alternate your logic in case of `navigateToName` is empty (e.g. modal is considered to be triggered by this card-item)
Anyway, if these cards will be used with vuex pages only, then make `navigateToName` required

2021-08-06 07:48 UTC, Sinu5oid commented on src/components/home/menu-list/menu-list-icon-item.vue
> +      type: String,
There is an enum `Modal` for making props typed (e.g. `Modal.SearchToken`)

2021-08-06 07:48 UTC, Sinu5oid commented on src/components/layout/content-wrapper.vue
> +      :inner-wrapper-style="leftRailStyle"
Where did the logo go?

2021-08-06 07:48 UTC, Sinu5oid commented on src/components/controls/nav-bar-item.vue
> +    navigateTo(): Record<string, string> {
`Route`, not `Record<string, string>`

2021-08-06 07:48 UTC, Sinu5oid commented on src/components/home/menu-list/menu-list-icon-item.vue
> +    handleOpenModal(): void {
rename as `handleClick`, if `this.modalId` is just an empty string -- emit an event to the parent

2021-08-06 07:48 UTC, Sinu5oid commented on src/components/layout/content-wrapper.vue
> +    leftRailStyle(): Record<string, string> {
Let's install `csstype` package (provides typings) and replace `Record<string, string>` with actual declarations here and everywhere you find any

2021-08-06 07:48 UTC, Sinu5oid commented on src/components/layout/left-rail/left-rail.vue
> +      default: {}
asaik, an empty object is not a valid prop initializer:

https://vuejs.org/v2/guide/components-props.html#Prop-Validation
```javascript
// Object with a default value
    propE: {
      type: Object,
      // Object or array defaults must be returned from
      // a factory function
      default: function () {
        return { message: 'hello' }
      }
    },
```

2021-08-06 07:48 UTC, Sinu5oid commented on src/components/sections/debit-card-section.vue
> +    :closed="!isInfoVisible"
It's better to use not inverted props
If the card should be opened by default, then it should have a valid initializer down in the store, not here

2021-08-06 07:48 UTC, Sinu5oid commented on src/components/sections/menu-section.vue
> +      <menu-list-icon-item
I think this should be used with `isFeatureEnabled('isBondsEnabled')`

2021-08-06 07:48 UTC, Sinu5oid commented on src/components/sections/menu-section.vue
> +      <menu-list-icon-item
This isn't available yet as well

2021-08-06 07:48 UTC, Sinu5oid commented on src/components/wallet-info-rail/wallet-info-rail.vue
> +    ...mapState('account', ['currentAddress'])
Please check why it's needed here `<transaction-list :address="currentAddress" />`
If there's no obvious reason and the prop is not used -- remove both mapper and prop

2021-08-06 07:48 UTC, Sinu5oid commented on src/components/sections/deposit-card-section.vue
> +  name: 'DepositCardSection',
This is Savings, so `SavingsDepositCardSection`

2021-08-06 07:48 UTC, Sinu5oid commented on src/components/sections/deposit-card-section.vue
> +    :btn-text="$t('depositCard.btnDepositCard')"
use `savings.*` prefix to keep semantics

2021-08-06 07:48 UTC, Sinu5oid commented on src/components/sections/menu-section.vue
> +        v-if="isFeatureEnabled('isBoundsEnabled')"
`bonds`, not `boUnds`

2021-08-06 07:48 UTC, Sinu5oid commented on src/store/modules/account/index.ts
>      isDebitCardSectionVisible: true,
change to false

2021-08-06 07:48 UTC, Sinu5oid commented on src/styles/_404.less
> +  font-family: 'Regular';
add `, sans-serif` generic font name as a fallback and `font-weight: 400`

2021-08-06 07:48 UTC, Sinu5oid commented on src/styles/_404.less
> +  font-family: 'Medium';
same here, but `font-weight` is `500`

2021-08-06 07:48 UTC, Sinu5oid commented on src/views/view-404.vue
> +      <p class="title">404</p>
This should be a heading
I think, `h1` (as the only one and the most important, describing the page in general) will do

2021-08-06 08:16 UTC, bog5651 commented on src/components/layout/content-wrapper.vue
> +      :inner-wrapper-style="leftRailStyle"
let it go
In new design its gone

2021-08-10 09:59 UTC, Sinu5oid approved these changes
Please resolve the remaining comments then merge. LGTM 🚀

2021-08-10 09:59 UTC, Sinu5oid commented on src/components/controls/card.vue
> +        @button-click="handleBtnClick"
We don't often use short names in the handlers/other code except for `transaction` -> `tx` and translation keys

2021-08-10 09:59 UTC, Sinu5oid commented on src/components/sections/header-balance-section/header-balance.vue
> +            <arrow-down-icon class="arrow" stroke="#3C3C4399" />
consider using v-once to freeze component state and make it DOM Entry without interactivity (at least this seems to be a perfect use-case as the props will never change)

2021-08-10 10:12 UTC, merged